#ifndef ARGUS_CAPABILITY_ABI_H
#define ARGUS_CAPABILITY_ABI_H

typedef enum {
    ARGUS_CAPABILITY_NONE = 0,
    ARGUS_CAPABILITY_CLOCK = 1,
    ARGUS_CAPABILITY_INPUT = 2,
    ARGUS_CAPABILITY_SURFACE = 3,
    ARGUS_CAPABILITY_IPC = 4,
    ARGUS_CAPABILITY_ANONYMOUS_STREAM = 5,
    ARGUS_CAPABILITY_RAW_NETWORK = 6,
} argus_capability_type_t;

#define ARGUS_CAP_RIGHT_READ (1u << 0)
#define ARGUS_CAP_RIGHT_WRITE (1u << 1)
#define ARGUS_CAP_RIGHT_WAIT (1u << 2)
#define ARGUS_CAP_RIGHT_PRESENT (1u << 3)
#define ARGUS_CAP_RIGHT_SEND (1u << 4)
#define ARGUS_CAP_RIGHT_RECEIVE (1u << 5)
#define ARGUS_CAP_RIGHT_CONNECT (1u << 6)

#endif
