#ifndef ARGUS_USER_SNAKE_GAME_H
#define ARGUS_USER_SNAKE_GAME_H

#define ARGUS_SNAKE_GRID_WIDTH 20u
#define ARGUS_SNAKE_GRID_HEIGHT 14u
#define ARGUS_SNAKE_CELL_COUNT \
    (ARGUS_SNAKE_GRID_WIDTH * ARGUS_SNAKE_GRID_HEIGHT)
#define ARGUS_SNAKE_MAX_LENGTH 96u

#define ARGUS_SNAKE_STATE_PLAYING 1u
#define ARGUS_SNAKE_STATE_GAME_OVER 2u

#endif
